### PR TITLE
edit numbers section

### PR DESCRIPTION
**Pull request by MAlngaawy**

### CODE REVIEW

**Comment by Nilegfx** [comment]
Please elaborate more on this PR and why you made it in the first place?

**Comment by Tramsi** [comment]
> Please elaborate more on this PR and why you made it in the first place?

in design numbers has a string afterwards : 'k', '+' , the content type is number so we are dealing with numbers and can't turn it to string because we are interpolating on the numbers because of the animation ... so the idea was to add the string conditionaly depending on the value of number ... it's more dynamic and mimics the design .... now it's just needs a little change to the logic and to the string itself and it would be perfect

**Comment by Tramsi** [comment]
> So if the number is bigger than 1000 just divide it by 1000 and add K to the End

**Comment by Tramsi** [comment]
Closed Pr by mistake

**Comment by Tramsi** [comment]
the white space befor the 'k' and '+' should be removed and also Magdy's comment is valid you should divide by 1000 in cases where number > 10000

**Pull request merged**
